### ISSUE TITLE
Cannot find 'ConsoleIO' in scope

### ISSUE THREAD

**Issue by marcosnathan** [paradiseduo/resymbol#2]
I'm getting this error when I execute ./build-macOS_x86.sh

**Comment by paradiseduo** [comment]
![image](https://user-images.githubusercontent.com/14846965/156955664-7a1eb697-03a8-4dc2-919a-70db2e9d90e3.png)

**Comment by ienthach** [comment]
i have same issue 

/Volumes/Data/github/resymbol/Sources/resymbol/Enum/Type.swift:21:13: error: cannot find 'ConsoleIO' in scope
            ConsoleIO.writeMessage("Please run 'lipo \(machoPath) -thin armv7 -output \(machoPath)_armv7' first", .error)
            ^~~~~~~~~

**Comment by paradiseduo** [comment]
> i have same issue
> 
> /Volumes/Data/github/resymbol/Sources/resymbol/Enum/Type.swift:21:13: error: cannot find 'ConsoleIO' in scope ConsoleIO.writeMessage("Please run 'lipo (machoPath) -thin armv7 -output (machoPath)_armv7' first", .error) ^~~~~~~~~

Now fixed, please git pull and build agine.
