### ISSUE TITLE
希望加入ios15通过LC_DYLD_CHAINED_FIXUPS 选项链接的app支持

### ISSUE THREAD

**Issue by DeleteMemoryyy** [paradiseduo/resymbol#5]
类似[dsdump/issues38](https://github.com/DerekSelander/dsdump/issues/38)和[dsdump/issues29](https://github.com/DerekSelander/dsdump/issues/29)中提到的需求，resymbol似乎对ios15中引入的新链接选项LC_DYLD_EXPORTS_TRIE和LC_DYLD_CHAINED_FIXUPS导致的dyld变化也无法处理？希望能支持面向新版本编译的app，感谢！

**Comment by paradiseduo** [comment]
在做了，还没发布

**Comment by DeleteMemoryyy** [comment]
> 在做了，还没发布

okok，工具非常好用

**Comment by paradiseduo** [comment]
已经发布，最新代码支持了
